In [1]:
import os

print("Kaggle input folders/files:")
print(os.listdir("/kaggle/input"))

Kaggle input folders/files:
['datasets']

In [2]:
import os

print("Files inside /kaggle/input/datasets:")
print(os.listdir("/kaggle/input/datasets"))

Files inside /kaggle/input/datasets:
['yukthajk']

In [3]:
import os

path = "/kaggle/input/datasets/yukthajk"

print("Files inside the dataset folder:")
print(os.listdir(path))

Files inside the dataset folder:
['ml-challenge']

In [4]:
import os

path = "/kaggle/input/datasets/yukthajk/ml-challenge"

print("Files inside ml-challenge:")
print(os.listdir(path))

Files inside ml-challenge:
['train_ground_truth.tsv', 'train_source3.tsv', 'train_source2.tsv', 'train_source1.tsv']

In [5]:
import pandas as pd

base_path = "/kaggle/input/datasets/yukthajk/ml-challenge/"

df_truth = pd.read_csv(
    base_path + "train_ground_truth.tsv",
    sep="\t"
)

print("Ground truth shape:", df_truth.shape)
print("\nColumns:")
print(df_truth.columns.tolist())

print("\nFirst 5 rows:")
display(df_truth.head())

Ground truth shape: (2206821, 2)

Columns:
['source1_entity_id', 'matched_entity_ids']

First 5 rows:

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

In [6]:
print("Missing values:")
print(df_truth.isna().sum())

print("\nNumber of unique Source 1 IDs:")
print(df_truth["source1_entity_id"].nunique())

print("\nNumber of unique ground-truth match entries:")
print(df_truth["matched_entity_ids"].nunique())

print("\nExamples of match patterns:")
print(df_truth["matched_entity_ids"].head(10).to_string())

Missing values:
source1_entity_id          0
matched_entity_ids    123247
dtype: int64

Number of unique Source 1 IDs:
2206821

Number of unique ground-truth match entries:
2083574

Examples of match patterns:
0    S2-681193310,S2-743505751,S3-775321672,S3-1129...
1    S2-249013014,S2-197070651,S3-478195123,S3-3843...
2               S2-790675320,S2-479876582,S3-878454467
3                S2-153058913,S2-24659151,S3-679606215
4    S2-478959098,S2-553508714,S2-625774905,S3-7280...
5    S2-755677256,S3-187831601,S3-641489370,S3-4762...
6                            S2-660036492,S3-804600254
7                            S3-274817120,S3-312496301
8                            S2-648035184,S3-588502663
9                S2-383871912,S3-74481402,S3-576451439

In [7]:
#load src1 
df_src1 = pd.read_csv(
    base_path + "train_source1.tsv",
    sep="\t"
)

print("Source 1 shape:", df_src1.shape)

print("\nColumns:")
print(df_src1.columns.tolist())

print("\nFirst 5 rows:")
display(df_src1.head())

Source 1 shape: (2206821, 4)

Columns:
['entity_id', 'business_name', 'business_address', 'country']

First 5 rows:

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India

In [8]:
truth_ids = set(df_truth["source1_entity_id"])
source1_ids = set(df_src1["entity_id"])

print("Ground-truth Source 1 IDs:", len(truth_ids))
print("Source 1 entity IDs:", len(source1_ids))

print("\nGround-truth IDs missing from Source 1:", len(truth_ids - source1_ids))
print("Source 1 IDs missing from ground truth:", len(source1_ids - truth_ids))

Ground-truth Source 1 IDs: 2206821
Source 1 entity IDs: 2206821

Ground-truth IDs missing from Source 1: 0
Source 1 IDs missing from ground truth: 0

In [9]:
df_src2 = pd.read_csv(
    base_path + "train_source2.tsv",
    sep="\t"
)

print("Source 2 shape:", df_src2.shape)

print("\nColumns:")
print(df_src2.columns.tolist())

print("\nFirst 5 rows:")
display(df_src2.head())

Source 2 shape: (5034616, 4)

Columns:
['entity_id', 'business_name', 'business_address', 'country']

First 5 rows:

,entity_id,business_name,business_address,country
0,S2-166376419,राम मार्केटिंग प्राइवेट लिमिटेड,"KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",India
1,S2-764573417,-- Holloway Peak Inc Seafood,"105 ELM ST, MORGANTON, NC",US
2,S2-639257739,आदित्य प्रॉपर्टीज एलएलपी,"G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh",India
3,S2-163963287,Summit Inc,"GREENSBORO, NC, 19 1/2 STARDUST TRAIL",US
4,S2-49942811,Delta Tetlecommunication Inc,"914 PIERPONT AVE, CLEVELAND, OH",US

In [10]:
print("Source 2 rows:", len(df_src2))

print("Unique Source 2 IDs:", df_src2["entity_id"].nunique())

print("Duplicate Source 2 IDs:",
      df_src2["entity_id"].duplicated().sum())

print("\nMissing values:")
print(df_src2.isna().sum())

Source 2 rows: 5034616
Unique Source 2 IDs: 5034616
Duplicate Source 2 IDs: 0

Missing values:
entity_id                0
business_name            2
business_address    168967
country                  0
dtype: int64

In [11]:
df_src3 = pd.read_csv(
    base_path + "train_source3.tsv",
    sep="\t"
)

print("Source 3 shape:", df_src3.shape)

print("\nColumns:")
print(df_src3.columns.tolist())

print("\nFirst 5 rows:")
display(df_src3.head())

Source 3 shape: (5285603, 4)

Columns:
['entity_id', 'business_name', 'business_address', 'country']

First 5 rows:

,entity_id,business_name,business_address,country
0,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US
1,S3-859268022,International South Consultants Private Ltd,NaN,India
2,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US
3,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US
4,S3-960981775,Pvt. EFS Print Ventures Ltd.,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...",India

In [12]:
print("Source 3 rows:", len(df_src3))

print("Unique Source 3 IDs:", df_src3["entity_id"].nunique())

print("Duplicate Source 3 IDs:",
      df_src3["entity_id"].duplicated().sum())

print("\nMissing values:")
print(df_src3.isna().sum())

Source 3 rows: 5285603
Unique Source 3 IDs: 5285603
Duplicate Source 3 IDs: 0

Missing values:
entity_id                0
business_name           13
business_address    175916
country                  0
dtype: int64

In [13]:
print(df_src3["country"].value_counts(dropna=False))

country
US       3170056
India    2115547
Name: count, dtype: int64

In [14]:
print("S3 IDs with correct prefix:",
      df_src3["entity_id"].str.startswith("S3-").sum())

print("Total Source 3 IDs:",
      len(df_src3))

print("\nExample IDs:")
print(df_src3["entity_id"].head(5).tolist())

S3 IDs with correct prefix: 5285603
Total Source 3 IDs: 5285603

Example IDs:
['S3-202863386', 'S3-859268022', 'S3-22467283', 'S3-671162755', 'S3-960981775']

In [15]:
print(df_truth["matched_entity_ids"].dropna().head(10).tolist())

['S2-681193310,S2-743505751,S3-775321672,S3-11291185,S3-860443364', 'S2-249013014,S2-197070651,S3-478195123,S3-384364074', 'S2-790675320,S2-479876582,S3-878454467', 'S2-153058913,S2-24659151,S3-679606215', 'S2-478959098,S2-553508714,S2-625774905,S3-728090388,S3-928796641,S3-449308785', 'S2-755677256,S3-187831601,S3-641489370,S3-476250621', 'S2-660036492,S3-804600254', 'S3-274817120,S3-312496301', 'S2-648035184,S3-588502663', 'S2-383871912,S3-74481402,S3-576451439']

In [16]:
match_counts = df_truth["matched_entity_ids"].str.count(",") + 1

# Rows with no match (NaN) should have 0 matches
match_counts = match_counts.fillna(0)

print("Rows with no matches:", (match_counts == 0).sum())
print("Rows with 1 match:", (match_counts == 1).sum())
print("Rows with 2 matches:", (match_counts == 2).sum())
print("Rows with 3 matches:", (match_counts == 3).sum())
print("Rows with 4+ matches:", (match_counts >= 4).sum())

print("\nMaximum matches in one row:", int(match_counts.max()))

Rows with no matches: 123247
Rows with 1 match: 119157
Rows with 2 matches: 375212
Rows with 3 matches: 530841
Rows with 4+ matches: 1058364

Maximum matches in one row: 11

In [17]:
s2_matches = df_truth["matched_entity_ids"].str.count("S2-").fillna(0)
s3_matches = df_truth["matched_entity_ids"].str.count("S3-").fillna(0)

print("Total Source 2 matches:", int(s2_matches.sum()))
print("Total Source 3 matches:", int(s3_matches.sum()))

print("\nRows with at least one Source 2 match:",
      int((s2_matches > 0).sum()))

print("Rows with at least one Source 3 match:",
      int((s3_matches > 0).sum()))

print("\nRows with both Source 2 and Source 3 matches:",
      int(((s2_matches > 0) & (s3_matches > 0)).sum()))

Total Source 2 matches: 3693619
Total Source 3 matches: 3944746

Rows with at least one Source 2 match: 1919076
Rows with at least one Source 3 match: 1940545

Rows with both Source 2 and Source 3 matches: 1776047

In [18]:
src2_ids = df_src2["entity_id"]
src3_ids = df_src3["entity_id"]

print("Source 2 IDs:", len(src2_ids))
print("Source 3 IDs:", len(src3_ids))

Source 2 IDs: 5034616
Source 3 IDs: 5285603

In [19]:
# Create sets of source IDs for fast lookup
src2_id_set = set(df_src2["entity_id"])
src3_id_set = set(df_src3["entity_id"])

missing_s2 = 0
missing_s3 = 0
checked_s2 = 0
checked_s3 = 0

chunk_size = 100_000

for start in range(0, len(df_truth), chunk_size):
    chunk = df_truth["matched_entity_ids"].iloc[start:start + chunk_size].dropna()

    for value in chunk:
        ids = value.split(",")

        for entity_id in ids:
            if entity_id.startswith("S2-"):
                checked_s2 += 1
                if entity_id not in src2_id_set:
                    missing_s2 += 1

            elif entity_id.startswith("S3-"):
                checked_s3 += 1
                if entity_id not in src3_id_set:
                    missing_s3 += 1

print("Checked Source 2 matches:", checked_s2)
print("Missing Source 2 IDs:", missing_s2)

print("\nChecked Source 3 matches:", checked_s3)
print("Missing Source 3 IDs:", missing_s3)

Checked Source 2 matches: 3693619
Missing Source 2 IDs: 0

Checked Source 3 matches: 3944746
Missing Source 3 IDs: 0

In [20]:
# Take a small sample of Source 1
sample = df_src1.sample(n=10000, random_state=42)

# Build a lookup from Source 2: (business_name, country) -> number of records
src2_name_country = (
    df_src2.groupby(["business_name", "country"], dropna=False)
           .size()
)

# Check how many Source 1 records have an exact name + country match in Source 2
keys = list(zip(sample["business_name"], sample["country"]))

exact_matches = [
    (name, country) in src2_name_country.index
    for name, country in keys
]

print("Sample Source 1 rows:", len(sample))
print("Exact name + country matches in Source 2:", sum(exact_matches))
print("Percentage:", round(sum(exact_matches) / len(sample) * 100, 2), "%")

Sample Source 1 rows: 10000
Exact name + country matches in Source 2: 2494
Percentage: 24.94 %

In [21]:
# Build a lookup using exact name + address + country
src2_name_address_country = (
    df_src2.groupby(
        ["business_name", "business_address", "country"],
        dropna=False
    ).size()
)

keys = list(zip(
    sample["business_name"],
    sample["business_address"],
    sample["country"]
))

exact_matches_address = [
    key in src2_name_address_country.index
    for key in keys
]

print("Sample Source 1 rows:", len(sample))
print(
    "Exact name + address + country matches in Source 2:",
    sum(exact_matches_address)
)
print(
    "Percentage:",
    round(sum(exact_matches_address) / len(sample) * 100, 2),
    "%"
)

Sample Source 1 rows: 10000
Exact name + address + country matches in Source 2: 0
Percentage: 0.0 %

In [22]:
# Show a few Source 1 records that have an exact name + country match
matched_sample = sample[exact_matches].head(5)

for _, row in matched_sample.iterrows():
    print("\nSOURCE 1")
    print("Name   :", row["business_name"])
    print("Address:", row["business_address"])
    print("Country:", row["country"])

    candidates = df_src2[
        (df_src2["business_name"] == row["business_name"]) &
        (df_src2["country"] == row["country"])
    ][["entity_id", "business_name", "business_address", "country"]].head(3)

    print("\nSOURCE 2 CANDIDATES")
    print(candidates.to_string(index=False))

SOURCE 1
Name   : Pediatric Medicine PLLC
Address: 4850 20, Otisco, NY
Country: US

SOURCE 2 CANDIDATES
   entity_id           business_name                  business_address country
S2-224665641 Pediatric Medicine PLLC 616 Walnut Creek Rd, DANVILLE, VA      US

SOURCE 1
Name   : Lakshmi Consultants Private Limited
Address: A-301, New Sai Dham Chsl, Ramdev Park Road, Thane, Maharashtra
Country: India

SOURCE 2 CANDIDATES
   entity_id                       business_name                                           business_address country
S2-513203400 Lakshmi Consultants Private Limited S NO 51/4 VISHWA ARCADE NR NAVALE LAWANS, PUNE, महाराष्ट्र   India
S2-689322580 Lakshmi Consultants Private Limited 15/82, NEAR OLD RAILWAY GATE KORATTY, MUKUNDAPURAM, Kerala   India

SOURCE 1
Name   : Ss Technology Private Limited
Address: Shop No. 1164, Pvt No.2, First Floor Kucha Mahajani, Chandni Chowk, Delhi, Central Delhi, Delhi
Country: India

SOURCE 2 CANDIDATES
   entity_id                 business_name                                                    business_address country
S2-175367589 Ss Technology Private Limited DOOR NO 191. 2ND FLOOR POCKET B SFS SUKHDEV VIHAR, NEW DELHI, Delhi   India

SOURCE 1
Name   : Heritage Society LLC
Address: 139 Fort Graham Road, Whitney, TX
Country: US

SOURCE 2 CANDIDATES
   entity_id        business_name                       business_address country
S2-137893852 Heritage Society LLC 19523 CHUPAROSA ROAD, APPLE VALLEY, CA      US

SOURCE 1
Name   : Slate PLLC
Address: 735 Charlton Street, Southbridge, MA
Country: US

SOURCE 2 CANDIDATES
   entity_id business_name                  business_address country
S2-658894340    Slate PLLC     4523 23RD ST, LITTLE ROCK, AR      US
S2-208388242    Slate PLLC   LA GRANGE, 125 MILAM STREET, TX      US
S2-502866346    Slate PLLC 1020 MEADOWLAND CT, BONDURANT, IA      US

In [23]:
# Count how many Source 2 records share each (business_name, country)
src2_name_counts = (
    df_src2.groupby(["business_name", "country"], dropna=False)
           .size()
)

# Look at the 10,000 Source 1 sample
sample_candidate_counts = []

for _, row in sample.iterrows():
    key = (row["business_name"], row["country"])
    sample_candidate_counts.append(
        src2_name_counts.get(key, 0)
    )

sample_candidate_counts = pd.Series(sample_candidate_counts)

print("No Source 2 candidate:",
      int((sample_candidate_counts == 0).sum()))

print("Exactly 1 candidate:",
      int((sample_candidate_counts == 1).sum()))

print("2-5 candidates:",
      int(sample_candidate_counts.between(2, 5).sum()))

print("More than 5 candidates:",
      int((sample_candidate_counts > 5).sum()))

print("\nMaximum candidates for one Source 1 record:",
      int(sample_candidate_counts.max()))

No Source 2 candidate: 7506
Exactly 1 candidate: 1186
2-5 candidates: 663
More than 5 candidates: 645

Maximum candidates for one Source 1 record: 158

In [24]:
import re

def normalize_text(text):
    if pd.isna(text):
        return ""
    text = str(text).lower()
    text = re.sub(r"[^a-z0-9]+", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

sample["name_norm"] = sample["business_name"].map(normalize_text)
sample["address_norm"] = sample["business_address"].map(normalize_text)

print(sample[[
    "business_name",
    "name_norm",
    "business_address",
    "address_norm"
]].head(5).to_string(index=False))

                            business_name                                 name_norm                                                                                              business_address                                                                                           address_norm
                  Pediatric Medicine PLLC                   pediatric medicine pllc                                                                                           4850 20, Otisco, NY                                                                                      4850 20 otisco ny
                     Fetech National Twin                      fetech national twin                                                                             19034 Woodburn Road, Woodburn, IN                                                                        19034 woodburn road woodburn in
           General Design Innovations LLC            general design innovations llc                                                                                   7241 Osage Avenue, Mesa, AZ                                                                              7241 osage avenue mesa az
Construction Ideaz Papers Private Limited construction ideaz papers private limited Building No.4/606, Prabhul Cottage Karimbalur, Elakamon, Ayiroor P.O., Thiruvananthapuram, Trivandrum, Kerala building no 4 606 prabhul cottage karimbalur elakamon ayiroor p o thiruvananthapuram trivandrum kerala
           Penaloza and Bittle First Inc.             penaloza and bittle first inc                                                                          4255 Charleswood Avenue, Memphis, TN                                                                     4255 charleswood avenue memphis tn

In [25]:
# Build normalized name + country lookup for Source 2
src2_name_norm_counts = (
    df_src2.assign(
        name_norm=df_src2["business_name"].map(normalize_text)
    )
    .groupby(["name_norm", "country"], dropna=False)
    .size()
)

# Count candidates for our 10,000 Source 1 sample
normalized_candidate_counts = []

for _, row in sample.iterrows():
    key = (row["name_norm"], row["country"])
    normalized_candidate_counts.append(
        src2_name_norm_counts.get(key, 0)
    )

normalized_candidate_counts = pd.Series(normalized_candidate_counts)

print("No normalized-name candidate:",
      int((normalized_candidate_counts == 0).sum()))

print("At least 1 normalized-name candidate:",
      int((normalized_candidate_counts > 0).sum()))

print("Exactly 1 candidate:",
      int((normalized_candidate_counts == 1).sum()))

print("2-5 candidates:",
      int(normalized_candidate_counts.between(2, 5).sum()))

print("More than 5 candidates:",
      int((normalized_candidate_counts > 5).sum()))

print("\nMaximum candidates:",
      int(normalized_candidate_counts.max()))

No normalized-name candidate: 4782
At least 1 normalized-name candidate: 5218
Exactly 1 candidate: 2321
2-5 candidates: 1704
More than 5 candidates: 1193

Maximum candidates: 223

In [28]:
from difflib import SequenceMatcher

row = sample.iloc[0]

print("SOURCE 1")
print("Name   :", row["business_name"])
print("Address:", row["business_address"])
print("Country:", row["country"])

candidates = df_src2[
    df_src2["country"] == row["country"]
].head(1000)

results = []

for _, candidate in candidates.iterrows():
    score = SequenceMatcher(
        None,
        row["name_norm"],
        normalize_text(candidate["business_name"])
    ).ratio() * 100

    results.append((
        score,
        candidate["entity_id"],
        candidate["business_name"],
        candidate["business_address"]
    ))

results.sort(reverse=True)

print("\nTop 10 name similarities:")

for score, entity_id, name, address in results[:10]:
    print(f"\nScore: {score:.1f}")
    print("ID:", entity_id)
    print("Name:", name)
    print("Address:", address)

SOURCE 1
Name   : Pediatric Medicine PLLC
Address: 4850 20, Otisco, NY
Country: US

Top 10 name similarities:

Score: 80.0
ID: S2-516249560
Name: Pediatric Medicine Partners
Address: #821 CARRIAGE HOUSE CIRCLE, EVNSVILLE, IN

Score: 67.9
ID: S2-699301561
Name: Chiropractic Medicine West LLC
Address: 1734 MARGARET LN, SALEM CITY, VA

Score: 63.6
ID: S2-598991538
Name: Family Medicine (L.L.C.)
Address: 04775 WILLIAMS DR, GEORGETOWN, TX

Score: 59.5
ID: S2-39079223
Name: Pediatric-Care
Address: 66 MURRAY ST, PO BOX 5644, BINGHAMTON, NY

Score: 58.2
ID: S2-699391872
Name: INTERNAL MEDICINE PHYSICIANS LLC
Address: 400  L COLEMAN DRIVE, MILLSBORO, DE

Score: 57.1
ID: S2-176968531
Name: Pediatric Dental Group Inc
Address: SEEKONK, #23 JUNIPER RD, MA

Score: 56.6
ID: S2-92868774
Name: Pediatric Dentistry Associates
Address: NC, 881 SHORE DR, SOUTHPORT

Score: 56.5
ID: S2-182591175
Name: Mcdougal & Medina P.L.L.C.
Address: TX, HOUSTON TONSHIP, 2704 KOWIS STREET

Score: 55.8
ID: S2-131872909
Name: Dermatology Medicine
Address: 317B LINCOLN HIGHWAY, DEKALB, IL

Score: 55.3
ID: S2-575166296
Name: Ames, Taylor & Mckinney LLC
Address: NY, 01080 87, CATSKILL

In [31]:
id="f7k2m1"

In [32]:
# Calculate address similarity for the same candidates

results_address = []

for _, candidate in candidates.iterrows():
    score = SequenceMatcher(
        None,
        row["address_norm"],
        normalize_text(candidate["business_address"])
    ).ratio() * 100

    results_address.append((
        score,
        candidate["entity_id"],
        candidate["business_name"],
        candidate["business_address"]
    ))

results_address.sort(reverse=True)

print("SOURCE 1 ADDRESS:")
print(row["business_address"])

print("\nTop 10 address similarities:")

for score, entity_id, name, address in results_address[:10]:
    print(f"\nScore: {score:.1f}")
    print("ID:", entity_id)
    print("Name:", name)
    print("Address:", address)

SOURCE 1 ADDRESS:
4850 20, Otisco, NY

Top 10 address similarities:

Score: 46.5
ID: S2-215156674
Name: Sydel Palacios Elite Iron Works
Address: 90 AVALON CIR, NESCONSET, NY

Score: 45.7
ID: S2-178867720
Name: PPX Infrastructure Holdings
Address: 2714 312, CORBIN, KY

Score: 44.4
ID: S2-857627805
Name: EYE ASSOCIATES, GROUP
Address: 240-A 2300, UT, OGDEN

Score: 44.4
ID: S2-347017935
Name: Regional Altisource Llc
Address: 4801 ORTEGA ST, SACRAMENTO, CA

Score: 44.4
ID: S2-172058052
Name: GSVISIONCOM
Address: 324 1/2 HARMONY MILLS LOFTS, COHOES, NY

Score: 43.9
ID: S2-912941112
Name: JEN ELWOOD ART5 CENTER
Address: 145 CR 2729, MICO CCDP, TX

Score: 43.8
ID: S2-466877271
Name: Livingston Direct 5ummit Inc
Address: 201 208, ROBY, TX

Score: 42.6
ID: S2-69394310
Name: heassociates.com
Address: 599 PEASE HILL ROAD, HORICON, NY

Score: 42.1
ID: S2-430367614
Name: Clarke Interstate Printing
Address: AL, 20 ALSTON ST, FOLEY

Score: 41.9
ID: S2-992673515
Name: Metropolitan Council Inc
Address: 6810 16 AVENUE, BROOKLYN, NY

In [33]:
# Get the ground-truth matches for our sample row

source1_id = row["entity_id"]

truth_row = df_truth[
    df_truth["source1_entity_id"] == source1_id
]["matched_entity_ids"].iloc[0]

print("Source 1 ID:", source1_id)
print("Source 1 name:", row["business_name"])
print("Source 1 address:", row["business_address"])

print("\nGround-truth matched IDs:")
print(truth_row)

Source 1 ID: S1-53356671
Source 1 name: Pediatric Medicine PLLC
Source 1 address: 4850 20, Otisco, NY

Ground-truth matched IDs:
S2-453334141,S2-904412198,S2-256033433,S3-468658814,S3-996978203

In [34]:
matched_ids = truth_row.split(",")

print("SOURCE 1")
print("ID      :", row["entity_id"])
print("Name    :", row["business_name"])
print("Address :", row["business_address"])
print("Country :", row["country"])

print("\nGROUND-TRUTH MATCHES")

for entity_id in matched_ids:
    if entity_id.startswith("S2-"):
        match = df_src2[df_src2["entity_id"] == entity_id]
    else:
        match = df_src3[df_src3["entity_id"] == entity_id]

    print("\n", match.to_string(index=False))

SOURCE 1
ID      : S1-53356671
Name    : Pediatric Medicine PLLC
Address : 4850 20, Otisco, NY
Country : US

GROUND-TRUTH MATCHES

    entity_id      business_name      business_address country
S2-453334141 Pediatric-Medicine 4850-C 20, OTISCO, NY      US

    entity_id           business_name      business_address country
S2-904412198 PLLC Pediatric Medirine 4850-C 20, OTISCO, NY      US

    entity_id      business_name         business_address country
S2-256033433 Pediatric Medicine 4850-C 20, LAFAYETTE, NY      US

    entity_id           business_name                  business_address country
S3-468658814 Pediatric Medicine PLLC 4850-4852 20, Lafayette, New York      US

    entity_id        business_name               business_address country
S3-996978203 Pediatric (Medicine) Otisco, New York, 4850-4852 20      US

In [35]:
def tokens(text):
    return set(normalize_text(text).split())

source1_address_tokens = tokens(row["business_address"])

print("SOURCE 1 ADDRESS TOKENS:")
print(source1_address_tokens)

print("\nGROUND-TRUTH ADDRESS OVERLAP:")

for entity_id in matched_ids:
    if entity_id.startswith("S2-"):
        match = df_src2[df_src2["entity_id"] == entity_id].iloc[0]
    else:
        match = df_src3[df_src3["entity_id"] == entity_id].iloc[0]

    match_tokens = tokens(match["business_address"])
    overlap = source1_address_tokens & match_tokens

    print(
        entity_id,
        "| shared tokens:", overlap,
        "| count:", len(overlap)
    )

SOURCE 1 ADDRESS TOKENS:
{'20', 'ny', 'otisco', '4850'}

GROUND-TRUTH ADDRESS OVERLAP:
S2-453334141 | shared tokens: {'20', 'ny', 'otisco', '4850'} | count: 4
S2-904412198 | shared tokens: {'20', 'ny', 'otisco', '4850'} | count: 4
S2-256033433 | shared tokens: {'20', 'ny', '4850'} | count: 3
S3-468658814 | shared tokens: {'20', '4850'} | count: 2
S3-996978203 | shared tokens: {'20', 'otisco', '4850'} | count: 3